data-collection:
  start_date: "01 january 2019"
  status: TRADING
  coin_pair: USDT
  data_folder: data
  reload: False

train_test_split_ratio: 0.8
col_num_values_threshold: 0.4

signals_parameters:
  default:
    rsi:
      lag: 1
      normalization_choice: 1
      window: 14

signals_optimizations:
  optuna_study_direction: maximize
  n_trials: 100
  n_trials_before_callback: 20
  param_to_optimize: sharpe_ratio
  commons:
    lag:
      min: 1
      max: 8
      step: 1
    normalization_choice:
      min: 1
      max: 5
      step: 1
  rsi:
    window:
      type: int
      min: 5
      max: 25
      step: 1
  stoch_rsi:
    window:
      type: int
      min: 5
      max: 25
      step: 1
    smooth1:
      type: int
      min: 1
      max: 6
      step: 1
    smooth2:
      type: int
      min: 1
      max: 6
      step: 1
  stoch_rsi_d:
    window:
      type: int
      min: 5
      max: 25
      step: 1
    smooth1:
      type: int
      min: 1
      max: 6
      step: 1
    smooth2:
      type: int
      min: 1
      max: 6
      step: 1
  stoch_rsi_k:
    window:
      type: int
      min: 5
      max: 25
      step: 1
    smooth1:
      type: int
      min: 1
      max: 6
      step: 1
    smooth2:
      type: int
      min: 1
      max: 6
      step: 1
  tsi:
    window_slow:
      type: int
      min: 20
      max: 30
      step: 1
    window_fast:
      type: int
      min: 7
      max: 17
      step: 1
  awesome_oscillator:
    window1:
      type: int
      min: 1
      max: 15
      step: 1
    window2:
      type: int
      min: 20
      max: 50
      step: 1
  kama:
    window:
      type: int
      min: 4
      max: 20
      step: 1
    pow1:
      type: int
      min: 2
      max: 8
      step: 1
    pow2:
      type: int
      min: 20
      max: 40
      step: 1
  stoch_oscillator:
    window:
      type: int
      min: 10
      max: 20
      step: 1
    smooth_window:
      type: int
      min: 2
      max: 8
      step: 1
  stoch_oscillator_signal:
    window:
      type: int
      min: 10
      max: 20
      step: 1
    smooth_window:
      type: int
      min: 2
      max: 8
      step: 1
  williams_r:
    lbp:
      type: int
      min: 5
      max: 21
      step: 1
  ppo:
    window_slow:
      type: int
      min: 20
      max: 30
      step: 1
    window_fast:
      type: int
      min: 12
      max: 18
      step: 1
    window_sign:
      type: int
      min: 4
      max: 9
      step: 1
  ppo_signal:
    window_slow:
      type: int
      min: 20
      max: 30
      step: 1
    window_fast:
      type: int
      min: 12
      max: 18
      step: 1
    window_sign:
      type: int
      min: 4
      max: 9
      step: 1
  pvo:
    window_slow:
      type: int
      min: 20
      max: 30
      step: 1
    window_fast:
      type: int
      min: 12
      max: 18
      step: 1
    window_sign:
      type: int
      min: 4
      max: 9
      step: 1
  pvo_signal:
    window_slow:
      type: int
      min: 20
      max: 30
      step: 1
    window_fast:
      type: int
      min: 12
      max: 18
      step: 1
    window_sign:
      type: int
      min: 4
      max: 9
      step: 1
  pvo_hist:
    window_slow:
      type: int
      min: 20
      max: 30
      step: 1
    window_fast:
      type: int
      min: 12
      max: 18
      step: 1
    window_sign:
      type: int
      min: 4
      max: 9
      step: 1
  roc:
    window:
      type: int
      min: 5
      max: 20
      step: 1
  macd_diff:
    window_slow:
      type: int
      min: 20
      max: 30
      step: 1
    window_fast:
      type: int
      min: 12
      max: 18
      step: 1
    window_sign:
      type: int
      min: 4
      max: 9
      step: 1
  macd_signal:
    window_slow:
      type: int
      min: 20
      max: 30
      step: 1
    window_fast:
      type: int
      min: 12
      max: 18
      step: 1
    window_sign:
      type: int
      min: 4
      max: 9
      step: 1
  aroon_up:
    window:
      type: int
      min: 10
      max: 30
      step: 1
  aroon_down:
    window:
      type: int
      min: 10
      max: 30
      step: 1
  cci:
    window:
      type: int
      min: 10
      max: 30
      step: 1
    constant:
      type: float
      min: 0.005
      max: 0.030
      step: 0.002
  dpo:
    window:
      type: int
      min: 10
      max: 30
      step: 1
  trix:
    window:
      type: int
      min: 5
      max: 25
      step: 1
  mass_index:
    window_fast:
      type: int
      min: 3
      max: 15
      step: 1
    window_slow:
      type: int
      min: 18
      max: 35
      step: 1
  bol_wband:
    window:
      type: int
      min: 12
      max: 30
      step: 1
    window_dev:
      type: int
      min: 2
      max: 5
      step: 1
  chaikin_money_flow:
    window:
      type: int
      min: 12
      max: 30
      step: 1
  ease_of_movement:
    window:
      type: int
      min: 5
      max: 21
      step: 1
  force_index:
    window:
      type: int
      min: 5
      max: 21
      step: 1
  money_flow_index:
    window:
      type: int
      min: 5
      max: 21
      step: 1

